minio:
  image: minio/minio
  environment:
  - MINIO_ACCESS_KEY
  - MINIO_SECRET_KEY
  command: server /export
  container_name: mlaas-compose-minio
  ports:
  - "9000:9000"
  volumes:
  - ./mlaas-minio-export:/export
  - ./mlaas-minio-config:/root/.minio
openzipkin:
  container_name: mlaas-compose-openzipkin
  image: openzipkin/zipkin
  ports:
  - "9411:9411"
etcd:
  container_name: mlaas-compose-etcd
  image: quay.io/coreos/etcd
  ports:
  - "2379:2379"
  - "2380:2380"
  - "4001:4001"
  command: "etcd -name etcd0 \
-advertise-client-urls http://${HostIP}:2379,http://${HostIP}:4001 \
-listen-client-urls http://0.0.0.0:2379,http://0.0.0.0:4001 \
-initial-advertise-peer-urls http://${HostIP}:2380 \
-listen-peer-urls http://0.0.0.0:2380 \
-initial-cluster-token etcd-cluster-1 \
-initial-cluster etcd0=http://${HostIP}:2380 \
-initial-cluster-state new"
